// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCJLNWh9sEFyK4vMjcaLOXQzQTOQ-uks',
    appId: '1:377877897782:web:12f850696528ae75dd2e97',
    messagingSenderId: '377877897782',
    projectId: 'linco-project-471db',
    authDomain: 'linco-project-471db.firebaseapp.com',
    storageBucket: 'linco-project-471db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2aWWazdHTcfwUF64tpvFbYYDJkfeIqfI',
    appId: '1:377877897782:android:2ed5fb1c63a05358dd2e97',
    messagingSenderId: '377877897782',
    projectId: 'linco-project-471db',
    storageBucket: 'linco-project-471db.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOornivRxX91tl-B0SRnZ1Xfr0y4-bRUM',
    appId: '1:377877897782:ios:79cc85c55d0bc217dd2e97',
    messagingSenderId: '377877897782',
    projectId: 'linco-project-471db',
    storageBucket: 'linco-project-471db.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOornivRxX91tl-B0SRnZ1Xfr0y4-bRUM',
    appId: '1:377877897782:ios:79cc85c55d0bc217dd2e97',
    messagingSenderId: '377877897782',
    projectId: 'linco-project-471db',
    storageBucket: 'linco-project-471db.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASCJLNWh9sEFyK4vMjcaLOXQzQTOQ-uks',
    appId: '1:377877897782:web:6e14525587340bccdd2e97',
    messagingSenderId: '377877897782',
    projectId: 'linco-project-471db',
    authDomain: 'linco-project-471db.firebaseapp.com',
    storageBucket: 'linco-project-471db.firebasestorage.app',
  );
}
